apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2024-07-04T06:12:11Z"
  name: browse-pvc
spec:
  description: Browse PVCs from the command line. Creates a job thats binds an unbound
    PVC and execs into it.
  homepage: https://github.com/clbx/kubectl-browse-pvc
  platforms:
  - bin: kubectl-browse-pvc
    files: null
    selector:
      matchLabels:
        os: darwin
    sha256: 71bd2a00dccf3b0c52220ecdc359e528b4aa5d5a789dc5d82e243aa729f58d13
    uri: https://github.com/clbx/kubectl-browse-pvc/releases/download/v1.0.5/kubectl-browse-pvc-darwin.zip
  - bin: kubectl-browse-pvc
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: f89676f545a2eca92418486a55805dd190021ee933be83f46d71a63d1179265d
    uri: https://github.com/clbx/kubectl-browse-pvc/releases/download/v1.0.5/kubectl-browse-pvc-linux.zip
  shortDescription: Browse PVC contents from the command line.
  version: v1.0.5
status:
  source:
    name: default
