apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2024-07-04T07:07:26Z"
  name: rbac-tool
spec:
  description: |-
    This plugin is a collection of RBAC tools to simplify analysis and configuration.
    You can visualize, analyze, query permissions as well as generate policies in multiple ways.

    Examples:
    # Generate HTML visualzation of your RBAC permissions
    kubectl rbac-tool viz

    # Query who can read secrets
    kubectl rbac-tool who-can get secret

    # Generate a ClusterRole policy that allows to read everything except secrets and services
    kubectl rbac-tool gen --deny-resources=secrets.,services. --allowed-verbs=get,list
  homepage: https://github.com/alcideio/rbac-tool
  platforms:
  - bin: rbac-tool
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: 15fc5bce21aa79393fa585fbd532b10b202c11129ee9201dd17a2ed9226f387d
    uri: https://github.com/alcideio/rbac-tool/releases/download/v1.19.0/rbac-tool_v1.19.0_linux_amd64.tar.gz
  - bin: rbac-tool
    files: null
    selector:
      matchLabels:
        arch: arm64
        os: linux
    sha256: 03ea811af1756b07280c25fa485f8b8530ab5a5e7929ea9d3174e160d0d76949
    uri: https://github.com/alcideio/rbac-tool/releases/download/v1.19.0/rbac-tool_v1.19.0_linux_arm64.tar.gz
  - bin: rbac-tool
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 48a379e5bfc5f2849424d57330ed32e05270fd4edc9a9abbf7dc516af3843fa1
    uri: https://github.com/alcideio/rbac-tool/releases/download/v1.19.0/rbac-tool_v1.19.0_darwin_amd64.tar.gz
  - bin: rbac-tool
    files: null
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: 26fcfa0623e2ccdc50fb3dac546b1cb4b095a60d5ccfa79ea7217a5a44ab3f52
    uri: https://github.com/alcideio/rbac-tool/releases/download/v1.19.0/rbac-tool_v1.19.0_darwin_arm64.tar.gz
  - bin: rbac-tool.exe
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: 50f352b9ff4f3f5cea091610612803aff7bb756d90d0222e007f2c7c2dd90a05
    uri: https://github.com/alcideio/rbac-tool/releases/download/v1.19.0/rbac-tool_v1.19.0_windows_amd64.tar.gz
  shortDescription: Plugin to analyze RBAC permissions and generate policies
  version: v1.19.0
status:
  source:
    name: default
