apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2024-07-04T01:40:24Z"
  name: score
spec:
  description: Kubernetes object analysis with recommendations for improved reliability
    and security.
  homepage: https://github.com/zegl/kube-score
  platforms:
  - bin: kube-score
    files:
    - from: kube-score
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
    sha256: 769daa94578fa6cd6553ec169b3f3fb74cf876f5c4c847b60c745f81da497dea
    uri: https://github.com/zegl/kube-score/releases/download/v1.18.0/kube-score_1.18.0_darwin_amd64.tar.gz
  - bin: kube-score
    files:
    - from: kube-score
      to: .
    - from: LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
    sha256: 2f4c3a43045ac4006fa1adcf970660828d2df09c4e9165bafe27d36479fa355a
    uri: https://github.com/zegl/kube-score/releases/download/v1.18.0/kube-score_1.18.0_linux_amd64.tar.gz
  shortDescription: Kubernetes static code analysis.
  version: v1.18.0
status:
  source:
    name: default
